Repository AY2223S1-CS2103T-T14-3/tp, pull requests merged in 2022-10, with the labels that each got.

#37 Implement a skeleton for the RecordList feature
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/Record.java
  src/main/java/seedu/address/model/person/RecordList.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: type.Enhancement, priority.High

#45 Add findr command
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/Logic.java
  src/main/java/seedu/address/logic/LogicManager.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/FindRecordCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/FindRecordCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Record.java
  src/main/java/seedu/address/model/person/RecordContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/RecordList.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/RecordCard.java
  src/main/java/seedu/address/ui/RecordListPanel.java
  src/main/resources/view/RecordListCard.fxml
  src/main/resources/view/RecordListPanel.fxml
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: type.Story, priority.High

#49 Implement DeleteRecordCommand
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/anthonyhoth.md
  docs/team/eiffellkf.md
  docs/team/hanwenlai.md
  docs/team/ljxsean.md
  docs/team/marclzh.md
  src/main/java/seedu/address/logic/commands/DeleteRecordCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/DeleteRecordCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/RecordList.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: priority.High

#50 Implement ClearRecordCommand
  .github/workflows/gradle.yml
  src/main/java/seedu/address/logic/commands/ClearRecordCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/RecordList.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: enhancement

#53 Update recordlist displayed in GUI
  src/main/java/seedu/address/ui/MainWindow.java
Labels: type.Bug, priority.High

#69 Add feature where Displayed Record List is always sorted by Date
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Record.java
  src/test/java/seedu/address/logic/commands/FindRecordCommandTest.java
Labels: enhancement, priority.Medium

#67 Add feature for adding appointment for users
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/ClearAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/CommandUtil.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/ListRecordCommand.java
  src/main/java/seedu/address/logic/parser/AddAppointmentCommandParser.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/ClearAppointmentCommandParser.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Appointment.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/RecordList.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: enhancement, priority.Medium

#79 Added Edit Record Functionality
  build.gradle
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/AddRecordCommand.java
  src/main/java/seedu/address/logic/commands/ClearRecordCommand.java
  src/main/java/seedu/address/logic/commands/DeleteRecordCommand.java
  src/main/java/seedu/address/logic/commands/EditRecordCommand.java
  src/main/java/seedu/address/logic/commands/FindRecordCommand.java
  src/main/java/seedu/address/logic/commands/ListRecordCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/EditRecordCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/DisplayedPerson.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/exceptions/DuplicateRecordException.java
  src/main/java/seedu/address/model/person/exceptions/RecordNotFoundException.java
  src/main/java/seedu/address/model/record/Record.java
  src/main/java/seedu/address/model/record/RecordList.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/EditRecordCommandTest.java
  src/test/java/seedu/address/logic/parser/DeleteRecordCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditRecordCommandParserTest.java
  src/test/java/seedu/address/testutil/EditRecordDescriptorBuilder.java
Labels: enhancement, priority.Medium

#81 Update UserGuide & DeveloperGuide
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
Labels: documentation, priority.Medium

#87 Add implementation of Find record mechanism in DeveloperGuide
  docs/DeveloperGuide.md
Labels: documentation

#80 Implement Birthdate field of a patient
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/ClearAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/EditCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Birthdate.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/model/person/BirthdateTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/PersonUtil.java
  src/test/java/seedu/address/testutil/RecordBuilder.java
  src/test/java/seedu/address/testutil/TestUtil.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: enhancement, priority.Medium

#84 Enhance `rfind` command
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/FindRecordCommand.java
  src/main/java/seedu/address/logic/parser/FindRecordCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/record/RecordContainsKeywordsPredicate.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FindRecordCommandParserTest.java
Labels: type.Enhancement, priority.Medium

#85 Add a `BackCommand`
  src/main/java/seedu/address/logic/commands/BackCommand.java
  src/main/java/seedu/address/logic/commands/Command.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/model/ModelManager.java
  src/test/java/seedu/address/logic/LogicManagerTest.java
  src/test/java/seedu/address/logic/commands/BackCommandTest.java
  src/test/java/seedu/address/logic/commands/EditRecordCommandTest.java
  src/test/java/seedu/address/logic/commands/ListCommandTest.java
Labels: enhancement, priority.Medium

#88 Update DG with AddRecordCommand implementation details
  build.gradle
  docs/DeveloperGuide.md
  docs/diagrams/AddRecordCommandSequenceDiagram.puml
  docs/images/AddRecordCommandSequenceDiagram.png
  src/main/java/seedu/address/MainApp.java
Labels: documentation

#89 Update DG with clear record command and appointment commands
  docs/DeveloperGuide.md
Labels: documentation

#90 Update DG with ListRecordCommand implementation details
  docs/DeveloperGuide.md
  docs/images/ListRecordSequenceDiagram.png
Labels: documentation

#95 Enhance add patient function's check for duplicate patients
  docs/UserGuide.md
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/logic/commands/AddRecordCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/DeleteCommand.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/EditRecordCommand.java
  src/main/java/seedu/address/logic/commands/FindCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/model/AddressBook.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/NameContainsKeywordsPredicate.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/person/UniquePersonList.java
  src/main/java/seedu/address/model/record/Record.java
  src/main/java/seedu/address/model/record/RecordList.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/model/AddressBookTest.java
  src/test/java/seedu/address/model/ModelManagerTest.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/model/person/UniquePersonListTest.java
  src/test/java/seedu/address/testutil/PersonUtil.java
Labels: bug, priority.Medium

#98 Update UG and Appointment Command Message
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddAppointmentCommand.java
  src/test/java/seedu/address/logic/commands/AddAppointmentCommandTest.java
Labels: documentation

#97 Update User Guide, showall and rfind
  docs/UserGuide.md
  src/main/java/seedu/address/commons/core/Messages.java
  src/main/java/seedu/address/logic/commands/CommandResult.java
  src/main/java/seedu/address/logic/commands/FindRecordCommand.java
  src/main/java/seedu/address/logic/commands/ShowAllCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/FindRecordCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/record/RecordContainsKeywordsPredicate.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/resources/view/MainWindow.fxml
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/commands/FindRecordCommandTest.java
  src/test/java/seedu/address/logic/commands/ShowAllCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FindRecordCommandParserTest.java
  src/test/java/seedu/address/logic/parser/ParserUtilTest.java
  src/test/java/seedu/address/model/record/RecordContainsKeywordsPredicateTest.java
Labels: priority.Medium

#100 Update DG for Edit Record and Delete Command
  docs/DeveloperGuide.md
  src/main/java/seedu/address/logic/commands/EditRecordCommand.java
Labels: documentation

#103 Fix Warning Message & Update Images in UG
  docs/UserGuide.md
  docs/images/Ui.png
  docs/images/findAlexDavidResult.png
  docs/images/helpMessage.png
  src/main/java/seedu/address/logic/commands/AddCommand.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/ui/HelpWindow.java
  src/test/java/seedu/address/logic/commands/AddCommandIntegrationTest.java
  src/test/java/seedu/address/logic/commands/AddCommandTest.java
Labels: bug

#102 Update DG for ListRecord and modify Birthdate field
  docs/diagrams/ListRecordSequenceDiagram.puml
  docs/images/ListRecordSequenceDiagram.png
  src/main/java/seedu/address/model/person/Birthdate.java
  src/test/java/seedu/address/model/person/BirthdateTest.java
Labels: bug, documentation

#104 Added Validation for Appointment Date and Reformatted UG
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddAppointmentCommand.java
  src/main/java/seedu/address/model/person/Appointment.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
  src/test/data/JsonSerializableAddressBookTest/typicalPersonsAddressBook.json
  src/test/java/seedu/address/logic/commands/AddAppointmentCommandTest.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/model/person/AppointmentTest.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
  src/test/java/seedu/address/testutil/TypicalPersons.java
Labels: bug, documentation

#105 Add date validation for Record and Birthdate
  src/main/java/seedu/address/logic/parser/AddAppointmentCommandParser.java
  src/main/java/seedu/address/logic/parser/AddRecordCommandParser.java
  src/main/java/seedu/address/logic/parser/EditRecordCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Appointment.java
  src/main/java/seedu/address/model/person/Birthdate.java
  src/main/java/seedu/address/model/record/Record.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/main/java/seedu/address/storage/JsonAdaptedRecord.java
  src/test/java/seedu/address/logic/commands/CommandTestUtil.java
  src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
  src/test/java/seedu/address/logic/parser/AddRecordCommandParserTest.java
  src/test/java/seedu/address/logic/parser/EditRecordCommandParserTest.java
  src/test/java/seedu/address/model/person/AppointmentTest.java
  src/test/java/seedu/address/model/person/BirthdateTest.java
  src/test/java/seedu/address/model/record/RecordTest.java
  src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
Labels: bug

#108 Change theme of UI
  docs/images/Ui.png
  docs/images/helpMessage.png
  src/main/java/seedu/address/logic/commands/AddRecordCommand.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/Extensions.css
  src/main/resources/view/HelpWindow.css
Labels: enhancement
