Repository AY2223S1-CS2103T-T14-3/tp, pull requests merged in 2022-11, with the labels that each got.

#145 Fix bug in help command
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/diagrams/UiClassDiagram.puml
  docs/images/ModelClassDiagram.png
  docs/images/StorageClassDiagram.png
  docs/images/UiClassDiagram.png
  src/main/java/seedu/address/logic/commands/HelpCommand.java
  src/main/java/seedu/address/ui/MainWindow.java
Labels: bug

#146 Fix UG Typo
  docs/UserGuide.md
Labels: documentation

#148 Fix UG header
  docs/UserGuide.md
Labels: bug, documentation

#147 Update UG & Error Messages Based on PE-D Issues
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/AddAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/AddRecordCommand.java
  src/main/java/seedu/address/logic/commands/Command.java
  src/main/java/seedu/address/logic/commands/EditRecordCommand.java
  src/main/java/seedu/address/logic/commands/ExitCommand.java
  src/main/java/seedu/address/logic/commands/FindRecordCommand.java
Labels: bug, documentation

#151 Rectify functionality bug
  src/main/java/seedu/address/model/person/Phone.java
  src/test/java/seedu/address/model/person/PhoneTest.java
Labels: bug, priority.High

#149 UG Bug fixes
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/_sass/minima/_base.scss
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/model/person/Appointment.java
  src/main/java/seedu/address/model/person/Birthdate.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/record/Record.java
  src/main/java/seedu/address/model/util/StringUtil.java
Labels: bug, documentation

#152 Add Illegal Spacing Check for Name and Address Parsing
  src/main/java/seedu/address/commons/util/StringUtil.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/model/person/Name.java
  src/main/java/seedu/address/model/util/StringUtil.java
Labels: bug

#154 UG & PPP Update
  README.md
  docs/UserGuide.md
  docs/images/CommandFormat.png
  docs/images/UiAnnotated.png
  docs/images/UiPatients.png
  docs/images/UiRecords.png
  docs/team/anthonyhoth.md
Labels: documentation

#155 Update PPP
  docs/team/marclzh.md
Labels: documentation

#156 Update PPP and UG
  docs/UserGuide.md
  docs/team/hanwenlai.md
Labels: documentation

#159 Fix formatting of UG
  docs/UserGuide.md
Labels: bug, documentation

#161 Fix formatting of DG
  docs/DeveloperGuide.md
Labels: documentation

#162 Update DG and UG
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/AddAppointmentSequenceDiagram.puml
  docs/diagrams/AppointmentActivityDiagram.puml
  docs/images/AddAppointmentSequenceDiagram.png
  docs/images/AppointmentActivityDiagram.png
  docs/team/eiffellkf.md
  docs/team/ljxsean.md
  docs/team/marclzh.md
Labels: documentation

#163 Fix formatting bugs in UG
  docs/DeveloperGuide.md
Labels: bug, documentation

#164 UG Edits
  docs/DeveloperGuide.md
  docs/SettingUp.md
  docs/UserGuide.md
  src/main/java/seedu/address/logic/commands/Command.java
Labels: documentation

#165 Edit PPP, add design considerations for Appointment Classes
  docs/DeveloperGuide.md
  docs/team/eiffellkf.md
  docs/team/marclzh.md
Labels: documentation

#166 Fix PPP
  docs/UserGuide.md
  docs/team/eiffellkf.md
  docs/team/marclzh.md
Labels: documentation

#167 Update PPP for anthonyhoth
  docs/team/anthonyhoth.md
Labels: documentation

#168 Update PPP for hanwenlai
  docs/team/hanwenlai.md
Labels: documentation

#169 Update PPP
  docs/team/marclzh.md
Labels: documentation

#170 Update Developer Guide and PPP
  docs/AboutUs.md
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/diagrams/FindRecordActivityDiagram.puml
  docs/diagrams/FindRecordSequenceDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/images/FindRecordActivityDiagram.png
  docs/images/FindRecordSequenceDiagram.png
  docs/images/ModelClassDiagram.png
  docs/team/ljxsean.md
Labels: documentation

#171 Update formatting of UG
  docs/UserGuide.md
  docs/_sass/minima/_base.scss
Labels: documentation

#172 Fix CSS of UG
  docs/UserGuide.md
  docs/_sass/minima/_base.scss
Labels: documentation

#174 Edit Image Alignment & Callouts of UG
  docs/UserGuide.md
  docs/_sass/minima/_base.scss
Labels: documentation

#173 Fix formatting of DG
  docs/DeveloperGuide.md
Labels: documentation

#176 Final 1.4 Fix
  docs/_sass/minima/_layout.scss
  docs/team/marclzh.md
  src/main/java/seedu/address/logic/commands/AddAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/ClearAppointmentCommand.java
  src/main/java/seedu/address/logic/commands/ClearCommand.java
  src/main/java/seedu/address/logic/commands/ClearRecordCommand.java
  src/main/java/seedu/address/logic/commands/CommandUtil.java
  src/main/java/seedu/address/model/person/Appointment.java
  src/main/java/seedu/address/model/record/Record.java
  src/main/java/seedu/address/model/record/RecordList.java
Labels: documentation

#178 Final v1.4 fix
  docs/team/hanwenlai.md
  src/main/java/seedu/address/logic/commands/ClearRecordCommand.java
  src/main/java/seedu/address/logic/commands/ListCommand.java
  src/main/java/seedu/address/logic/commands/ListRecordCommand.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/model/person/Birthdate.java
Labels: enhancement

#186 Update PPP
  docs/team/anthonyhoth.md
  docs/team/eiffellkf.md
  docs/team/hanwenlai.md
  docs/team/ljxsean.md
  docs/team/marclzh.md
Labels: documentation

#189 Fix Alignment of UG
  docs/UserGuide.md
Labels: documentation

#190 Fix Alignment of Images in UG
  docs/UserGuide.md
Labels: documentation

#191 Fix Image & Add Links to UG
  docs/UserGuide.md
Labels: documentation

#192 Change Navigation section in UG
  docs/UserGuide.md
Labels: documentation

#194 Fill up missing desc. section in UG
  docs/UserGuide.md
Labels: documentation
